apiVersion: platform.confluent.io/v1beta1
kind: SchemaRegistry
metadata:
  name: sr
spec:
  license:
    globalLicense: true
  replicas: 1
  image:
    application: confluentinc/cp-schema-registry:7.4.0
    init: confluentinc/confluent-init-container:2.6.0
  tls:
    secretRef: tls-sr
  authorization:
    type: rbac
  configOverrides:
    jvm:
      - -XX:+UseG1GC
  dependencies:
    mds:
      endpoint: https://kafka:8090
      tokenKeyPair:
        secretRef: mds-token
      authentication:
        type: bearer
        bearer:
          secretRef: mds-sr
      tls:
        enabled: true
    kafka:
      authentication:
        type: oauthbearer
        oauthbearer:
          secretRef: mds-sr
      bootstrapEndpoint: kafka:9073
      tls:
        enabled: true
  passwordEncoder:
    secretRef: password-encoder-secret
  enableSchemaExporter: true
  podTemplate:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: app
                  operator: In
                  values:
                    - general
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - sr

