kind: ConfluentRolebinding
apiVersion: platform.confluent.io/v1beta1
metadata:
  name: admins-sysadm-1
  labels:
    principal: admins
    role: systemadmin
    cscope: kafkaconnect
spec:
  principal:
    name: admins
    type: group
  clustersScopeByIds:
    connectClusterId: confluent.connect
  role: SystemAdmin
---
