kind: ConfluentRolebinding
apiVersion: platform.confluent.io/v1beta1
metadata:
  name: admins-sysadm-2
  labels:
    principal: admins
    role: systemadmin
    cscope: kafkasr
spec:
  principal:
    name: admins
    type: group
  clustersScopeByIds:
    schemaRegistryClusterId: id_sr_confluent
  role: SystemAdmin
