kind: ConfluentRolebinding
apiVersion: platform.confluent.io/v1beta1
metadata:
  name: admins-sysadm-3
  labels:
    principal: admins
    role: systemadmin
    cscope: kafkaksql
spec:
  principal:
    name: admins
    type: group
  clustersScopeByIds:
    ksqlClusterId: confluent.ksql_
  role: SystemAdmin
---
