apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../11_kraft

patches:
  - target:
      group: platform.confluent.io
      version: v1beta1
      kind: KRaftController
    path: kafka.yml
