
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization




resources:
  - namespace.yml





helmCharts:
  - name: ingress-nginx
    namespace: ingress-nginx
    version: 4.6.0
    repo: https://kubernetes.github.io/ingress-nginx
    releaseName: ingress-nginx
    valuesInline:
      controller:
        extraArgs:
          enable-ssl-passthrough: true

    includeCRDs: true
