apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../bases/exporters

patches:
  - target:
      kind: SchemaExporter
      group: platform.confluent.io
    path: se001.yml