kind: ConfluentRolebinding
apiVersion: platform.confluent.io/v1beta1
metadata:
  name: evntsuper-sysadm-2
  labels:
    principal: nermin
    role: systemadmin
    cscope: kafkasr
spec:
  principal:
    name: nermin
    type: user
  clustersScopeByIds:
    schemaRegistryClusterId: id_sr_confluent
  role: SystemAdmin
---
