kind: ConfluentRolebinding
apiVersion: platform.confluent.io/v1beta1
metadata:
  name: evntsuper-sysadm-3
  labels:
    principal: nermin
    role: systemadmin
    cscope: kafkaksql
spec:
  principal:
    name: nermin
    type: user
  clustersScopeByIds:
    ksqlClusterId: confluent.ksql_
  role: SystemAdmin
---
