apiVersion: platform.confluent.io/v1beta1
kind: KsqlDB
metadata:
  name: ksql
  
spec:
  authorization:
    type: rbac
  license:
    globalLicense: true
  podTemplate:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: app
                  operator: In
                  values:
                    - general
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - ksql
    resources:
      requests:
        cpu: 500m
        memory: 516Mi
  replicas: 1
  image:
    application: confluentinc/cp-ksqldb-server:7.4.1
    init: confluentinc/confluent-init-container:2.6.1
  dataVolumeCapacity: 10Gi
  storageClass:
    name: cfk-storage-delete
  tls:
    secretRef: tls-ksql
  configOverrides:
    jvm:
      - -XX:+UseG1GC
  dependencies:
    schemaRegistry:
      url: https://sr:8081
      tls:
        enabled: true
    connect:
      url: https://connect:8083
      tls:
        enabled: true
    kafka:
      discovery:
        name: kafka
      tls:
        enabled: true
      authentication:
        type: mtls
    mds:
      endpoint: https://kafka:8090
      tokenKeyPair:
        secretRef: mds-token
      authentication:
        type: bearer
        bearer:
          secretRef: mds-ksql
      tls:
        enabled: true

    interceptor:
      enabled: true

