# Default pipeline from cli
steps:


- label: ":kafka::k8s: (DEV) Build cfrbs :kafka::superfly:"
  commands:
    - kustomize build ps-cfk-app/environments/0_dev/cfrbs > /dev/null
  plugins:
    - docker#v5.8.0:
        image: dedovicnermin/pscfk-buildkite:0.0.4



- label: ":kafka::k8s: (DEV) Build datagen_connectors :kafka::superfly:"
  commands:
    - kustomize build ps-cfk-app/environments/0_dev/datagen_connectors > /dev/null
  plugins:
    - docker#v5.8.0:
        image: dedovicnermin/pscfk-buildkite:0.0.4


- label: ":kafka::k8s: (DEV) Build CP->CC w/ ClusterLink + Schema Exporter :kafka::superfly:"
  commands:
    - kustomize build ps-cfk-app/environments/0_dev/cfk_cc_clusterlink/step_0 > /dev/null
    - kustomize build ps-cfk-app/environments/0_dev/cfk_cc_clusterlink/step_1 > /dev/null
  plugins:
    - docker#v5.8.0:
        image: dedovicnermin/pscfk-buildkite:0.0.4



- label: ":kafka::k8s: (DEV) Build ADLS2 Sink Connectors :kafka::superfly:"
  commands:
    - kustomize build ps-cfk-app/environments/0_dev/connectors/adls2/avro_value/daily > /dev/null
    - kustomize build ps-cfk-app/environments/0_dev/connectors/adls2/avro_value/default > /dev/null
    - kustomize build ps-cfk-app/environments/0_dev/connectors/adls2/avro_value/field > /dev/null
    - kustomize build ps-cfk-app/environments/0_dev/connectors/adls2/avro_value/hourly > /dev/null
    - kustomize build ps-cfk-app/environments/0_dev/connectors/adls2/avro_value/hourly_recordtime > /dev/null
    - kustomize build ps-cfk-app/environments/0_dev/connectors/adls2/avro_value/timebased > /dev/null
    - kustomize build ps-cfk-app/environments/0_dev/connectors/adls2/avro_value/timebased_compact > /dev/null
    - kustomize build ps-cfk-app/environments/0_dev/connectors/adls2/avro_value/timebased_compact > /dev/null
  plugins:
    - docker#v5.8.0:
        image: dedovicnermin/pscfk-buildkite:0.0.4



