apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: test

resources:
  - ../../../../overlays/1_test/exporters/dev_to_test
  - ../../../../overlays/1_test/connectors/replicator/dev_to_test
