apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yml



helmCharts:
  - name: datadog
    namespace: datadog
    releaseName: datadog
    repo: https://helm.datadoghq.com
    includeCRDs: true
    version: 3.23.0
    valuesFile: values.yml
