apiVersion: platform.confluent.io/v1beta1
kind: Connector
metadata:
  name: oracdc001
spec:
  class: io.confluent.connect.oracle.cdc.OracleCdcSourceConnector
  configs:
    oracle.server: oracle-svc.oracle
    oracle.port: 1521
    oracle.sid: ORCLCDB
    oracle.pdb.name: ORCLPDB1
    oracle.username: C##MYUSER
    oracle.password: mypassword
    start.from: snapshot
#    redo.log.topic.name: ${connectorName}-redo-log
    redo.log.consumer.bootstrap.servers: kafka:9073
    table.inclusion.regex: |
      ORCLPDB1[.].*[.](CUSTOMERS | REGIONS | COUNTRIES)
#    table.topic.name.template: ${databaseName}.${schemaName}.${tableName}
    numeric.mapping: best_fit


    connection.pool.max.size: 20
    redo.log.row.fetch.size: 5000
    oracle.dictionary.mode: auto
#    topic.creation.redo.include: redo-log-topic-001
#    topic.creation.redo.replication.factor: 1
#    topic.creation.redo.partitions: 1
#    topic.creation.redo.cleanup.policy": delete
#    topic.creation.redo.retention.ms": 1209600000
    topic.creation.default.replication.factor: 3
    topic.creation.default.partitions: 1
    topic.creation.default.cleanup.policy: delete