apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: krp-cert
spec:
  commonName: krp
  dnsNames:
    - 'krp'

    - 'krp.confluent'
    - 'krp.dev'
    - 'krp.test'
    - 'krp.qa'
    - 'krp.prod'
    - 'krp.dr'

    - 'krp.confluent.svc'
    - 'krp.dev.svc'
    - 'krp.test.svc'
    - 'krp.qa.svc'
    - 'krp.prod.svc'
    - 'krp.dr.svc'

    - 'krp.confluent.svc.cluster.local'
    - 'krp.dev.svc.cluster.local'
    - 'krp.test.svc.cluster.local'
    - 'krp.qa.svc.cluster.local'
    - 'krp.prod.svc.cluster.local'
    - 'krp.dr.svc.cluster.local'

    - '*.krp.confluent.svc.cluster.local'
    - '*.krp.dev.svc.cluster.local'
    - '*.krp.test.svc.cluster.local'
    - '*.krp.qa.svc.cluster.local'
    - '*.krp.prod.svc.cluster.local'
    - '*.krp.dr.svc.cluster.local'

    - 'krp.confluent.kafka.confluentps.io'
    - 'krp.dr.kafka.confluentps.io'
    - 'krp.dev.kafka.confluentps.io'
    - 'krp.test.kafka.confluentps.io'
    - 'krp.qa.kafka.confluentps.io'
    - 'krp.prod.kafka.confluentps.io'
    - 'krp.kafka.confluentps.io'
    - 'krp.confluent.gke.confluentps.io'
    - 'krp.dr.gke.confluentps.io'
    - 'krp.dev.gke.confluentps.io'
    - 'krp.test.gke.confluentps.io'
    - 'krp.qa.gke.confluentps.io'
    - 'krp.prod.gke.confluentps.io'
    - 'krp.gke.confluentps.io'

    - 'krp.confluent.eks.confluentps.io'
    - 'krp.dr.eks.confluentps.io'
    - 'krp.dev.eks.confluentps.io'
    - 'krp.test.eks.confluentps.io'
    - 'krp.qa.eks.confluentps.io'
    - 'krp.prod.eks.confluentps.io'
    - 'krp.eks.confluentps.io'

    - 'krp.confluent.aks.confluentps.io'
    - 'krp.dr.aks.confluentps.io'
    - 'krp.dev.aks.confluentps.io'
    - 'krp.test.aks.confluentps.io'
    - 'krp.qa.aks.confluentps.io'
    - 'krp.prod.aks.confluentps.io'
    - 'krp.aks.confluentps.io'

    - 'krp.confluent.local.confluentps.io'
    - 'krp.dr.local.confluentps.io'
    - 'krp.dev.local.confluentps.io'
    - 'krp.test.local.confluentps.io'
    - 'krp.qa.local.confluentps.io'
    - 'krp.prod.local.confluentps.io'
    - 'krp.local.confluentps.io'
  renewBefore: 24h
  duration: 17520h # two years
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
  issuerRef:
    kind: ClusterIssuer
    name: ca-issuer
    group: cert-manager.io
  secretName: tls-krp

