apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ksql-cert
spec:
  commonName: ksql
  dnsNames:
    - 'ksql'

    - 'ksql.confluent'
    - 'ksql.dev'
    - 'ksql.test'
    - 'ksql.qa'
    - 'ksql.prod'
    - 'ksql.de'

    - 'ksql.confluent.svc'
    - 'ksql.dev.svc'
    - 'ksql.test.svc'
    - 'ksql.qa.svc'
    - 'ksql.prod.svc'
    - 'ksql.dr.svc'

    - 'ksql.confluent.svc.cluster.local'
    - 'ksql.dev.svc.cluster.local'
    - 'ksql.test.svc.cluster.local'
    - 'ksql.qa.svc.cluster.local'
    - 'ksql.prod.svc.cluster.local'
    - 'ksql.dr.svc.cluster.local'

    - '*.ksql.confluent.svc.cluster.local'
    - '*.ksql.dev.svc.cluster.local'
    - '*.ksql.test.svc.cluster.local'
    - '*.ksql.qa.svc.cluster.local'
    - '*.ksql.prod.svc.cluster.local'
    - '*.ksql.dr.svc.cluster.local'

    - 'ksql.kafka.confluentps.io'
    - 'ksql.confluent.kafka.confluentps.io'
    - 'ksql.dev.kafka.confluentps.io'
    - 'ksql.test.kafka.confluentps.io'
    - 'ksql.qa.kafka.confluentps.io'
    - 'ksql.prod.kafka.confluentps.io'
    - 'ksql.dr.kafka.confluentps.io'

    - '*.ksql.kafka.confluentps.io'
    - '*.ksql.confluent.kafka.confluentps.io'
    - '*.ksql.dev.kafka.confluentps.io'
    - '*.ksql.test.kafka.confluentps.io'
    - '*.ksql.qa.kafka.confluentps.io'
    - '*.ksql.prod.kafka.confluentps.io'
    - '*.ksql.dr.kafka.confluentps.io'

    - 'ksql.confluent.kafka.confluentps.io'
    - 'ksql.dr.kafka.confluentps.io'
    - 'ksql.dev.kafka.confluentps.io'
    - 'ksql.test.kafka.confluentps.io'
    - 'ksql.qa.kafka.confluentps.io'
    - 'ksql.prod.kafka.confluentps.io'
    - 'ksql.kafka.confluentps.io'
    - 'ksql.confluent.gke.confluentps.io'
    - 'ksql.dr.gke.confluentps.io'
    - 'ksql.dev.gke.confluentps.io'
    - 'ksql.test.gke.confluentps.io'
    - 'ksql.qa.gke.confluentps.io'
    - 'ksql.prod.gke.confluentps.io'
    - 'ksql.gke.confluentps.io'
    - 'ksql.confluent.eks.confluentps.io'
    - 'ksql.dr.eks.confluentps.io'
    - 'ksql.dev.eks.confluentps.io'
    - 'ksql.test.eks.confluentps.io'
    - 'ksql.qa.eks.confluentps.io'
    - 'ksql.prod.eks.confluentps.io'
    - 'ksql.eks.confluentps.io'

    - 'ksql.confluent.aks.confluentps.io'
    - 'ksql.dr.aks.confluentps.io'
    - 'ksql.dev.aks.confluentps.io'
    - 'ksql.test.aks.confluentps.io'
    - 'ksql.qa.aks.confluentps.io'
    - 'ksql.prod.aks.confluentps.io'
    - 'ksql.aks.confluentps.io'

    - 'ksql.confluent.local.confluentps.io'
    - 'ksql.dr.local.confluentps.io'
    - 'ksql.dev.local.confluentps.io'
    - 'ksql.test.local.confluentps.io'
    - 'ksql.qa.local.confluentps.io'
    - 'ksql.prod.local.confluentps.io'
    - 'ksql.local.confluentps.io'
  renewBefore: 24h
  duration: 17520h # two years
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
  issuerRef:
    kind: ClusterIssuer
    name: ca-issuer
    group: cert-manager.io
  secretName: tls-ksql