apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kafka-cert
spec:
  commonName: kafka
  dnsNames:
    - 'kafka'

    - 'kafka.confluent'
    - 'kafka.dev'
    - 'kafka.test'
    - 'kafka.qa'
    - 'kafka.prod'
    - 'kafka.dr'

    - 'kafka.confluent.svc'
    - 'kafka.dev.svc'
    - 'kafka.test.svc'
    - 'kafka.qa.svc'
    - 'kafka.prod.svc'
    - 'kafka.dr.svc'

    - 'kafka.confluent.svc.cluster.local'
    - 'kafka.dev.svc.cluster.local'
    - 'kafka.test.svc.cluster.local'
    - 'kafka.qa.svc.cluster.local'
    - 'kafka.prod.svc.cluster.local'
    - 'kafka.dr.svc.cluster.local'

    - '*.kafka.confluent.svc.cluster.local'
    - '*.kafka.dev.svc.cluster.local'
    - '*.kafka.test.svc.cluster.local'
    - '*.kafka.qa.svc.cluster.local'
    - '*.kafka.prod.svc.cluster.local'
    - '*.kafka.dr.svc.cluster.local'

    - '*.confluent.kafka.confluentps.io'
    - '*.dr.kafka.confluentps.io'
    - '*.dev.kafka.confluentps.io'
    - '*.test.kafka.confluentps.io'
    - '*.qa.kafka.confluentps.io'
    - '*.prod.kafka.confluentps.io'
    - '*.kafka.confluentps.io'
    - '*.confluent.gke.confluentps.io'
    - '*.dr.gke.confluentps.io'
    - '*.dev.gke.confluentps.io'
    - '*.test.gke.confluentps.io'
    - '*.qa.gke.confluentps.io'
    - '*.prod.gke.confluentps.io'
    - '*.gke.confluentps.io'
    - '*.confluent.eks.confluentps.io'
    - '*.dr.eks.confluentps.io'
    - '*.dev.eks.confluentps.io'
    - '*.test.eks.confluentps.io'
    - '*.qa.eks.confluentps.io'
    - '*.prod.eks.confluentps.io'
    - '*.eks.confluentps.io'

    - '*.confluent.aks.confluentps.io'
    - '*.dr.aks.confluentps.io'
    - '*.dev.aks.confluentps.io'
    - '*.test.aks.confluentps.io'
    - '*.qa.aks.confluentps.io'
    - '*.prod.aks.confluentps.io'
    - '*.aks.confluentps.io'

    - '*.confluent.local.confluentps.io'
    - '*.dr.local.confluentps.io'
    - '*.dev.local.confluentps.io'
    - '*.test.local.confluentps.io'
    - '*.qa.local.confluentps.io'
    - '*.prod.local.confluentps.io'
    - '*.local.confluentps.io'
  renewBefore: 24h
  duration: 17520h # two hours
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
  issuerRef:
    kind: ClusterIssuer
    name: ca-issuer
    group: cert-manager.io
  secretName: tls-kafka
