apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  schema: avro
  plugin: datagen

resources:
  - avro.shoe.clicks.yml
  - ../../../../../connectors_generic/source/community/with_sr


patches:
  - target:
      kind: Connector
      labelSelector: conntype=source
    path: avro-shoe-clicks.yml
  - target:
      kind: Connector
      name: basesr
    patch: |-
      - op: replace
        path: /metadata/name
        value: avro.shoe.clickstream
        
