apiVersion: platform.confluent.io/v1beta1
kind: Connector
metadata:
  name: avro.shoe.customer
  labels:
    family: shoes
spec:
  class: "io.confluent.kafka.connect.datagen.DatagenConnector"
  taskMax: 1
  configs:
    kafka.topic: "avro.shoe.customers"
    quickstart: "shoe_customers"
    key.converter: "org.apache.kafka.connect.storage.StringConverter"
    value.converter: "io.confluent.connect.avro.AvroConverter"
    max.interval: "60000"
    iterations: "10000"
    schema.compatibility: "BACKWARD"


