apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: avro.field.mngnt.sensors
spec:
  replicas: 3
  partitionCount: 1
  kafkaClusterRef:
    name: kafka
  kafkaRestClassRef:
    name: default
