apiVersion: platform.confluent.io/v1beta1
kind: ControlCenter
metadata:
  name: c3
spec:
  authorization:
    type: rbac
  replicas: 1
  image:
    application: confluentinc/cp-enterprise-control-center:7.5.0
    init: confluentinc/confluent-init-container:2.7.0
  license:
    globalLicense: true
  configOverrides:
    jvm:
      - -XX:+UseG1GC
      - -XX:MaxRAMPercentage=70
  dataVolumeCapacity: 10Gi
  tls:
    secretRef: tls-c3

  podTemplate:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: app
                  operator: In
                  values:
                    - general
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - c3
    resources:
      requests:
        cpu: 2
        memory: 1Gi
  dependencies:
    kafka:
      bootstrapEndpoint: kafka:9073
      authentication:
        type: oauthbearer
        oauthbearer:
          secretRef: mds-c3
      tls:
        enabled: true
    mds:
      endpoint: https://kafka:8090
      tokenKeyPair:
        secretRef: mds-token
      authentication:
        type: bearer
        bearer:
          secretRef: mds-c3
      tls:
        enabled: true
    connect:
      - name: connect
        url: https://connect:8083
        tls:
          enabled: true
    ksqldb:
      - name: ksql
        url: https://ksql:8088
        tls:
          enabled: true
    schemaRegistry:
      url: https://sr:8081
      tls:
        enabled: true
