apiVersion: v1
data:
  telemetry.txt: YXBpLmtleT00NVdJUlhSRklFSTRBVllNCmFwaS5zZWNyZXQ9QXZoVUhzVDFJN2tLZkdBTXVUL3RVWDhoZmg0ZTFkNWFzSTlUSjVwQitCK1Y3ZjdQbURVWGt1ek03cHppbmRPdQ==
kind: Secret
metadata:
  name: telemetry-secret

