apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev
resources:
  - ../../../../overlays/0_dev/cfk_cc_clusterlink/exporters
  - ../../../../overlays/0_dev/cfk_cc_clusterlink/links

patches:
  - target:
      group: platform.confluent.io
      version: v1beta1
      kind: SchemaExporter
    patch: |-
      - op: replace
        path: /spec/destinationCluster/schemaRegistryRest/endpoint
        value: https://psrc-vn38j.us-east-2.aws.confluent.cloud
  - target:
      group: platform.confluent.io
      version: v1beta1
      kind: ClusterLink
      name: cfkcl-src
    patch: |-
      - op: replace
        path: /spec/destinationKafkaCluster/clusterID
        value: lkc-3nwjyw
      - op: replace
        path: /spec/destinationKafkaCluster/bootstrapEndpoint
        value: pkc-qvo1m.us-west-2.aws.confluent.cloud:9092