apiVersion: platform.confluent.io/v1beta1
kind: ControlCenter
metadata:
  name: c3
spec:
  authorization:
    type: rbac
  dataVolumeCapacity: 10Gi
  configOverrides:
    server:
      - confluent.controlcenter.mds.client.max.requests.queued.per.destination=2048
      - confluent.controlcenter.mode.enable=management
      - confluent.controlcenter.command.topic.replication=1
      - confluent.controlcenter.replication.factor=1
      - confluent.metrics.reporter.topic.replicas=1
      - confluent.metrics.topic.replication=1
      - confluent.monitoring.interceptor.topic.replication=1
      - confluent.controlcenter.internal.topics.replication=1
  #      - confluent.controlcenter.streams.confluent.metadata.enable.server.urls.refresh=false
  #      - confluent.metadata.enable.server.urls.refresh=false
  podTemplate:
    resources:
      requests:
        cpu: 1.0
        memory: 1Gi
  dependencies:
    kafka:
      bootstrapEndpoint: kafka.dev.svc.cluster.local:9073
      authentication:
        type: oauthbearer
        oauthbearer:
          secretRef: mds-c3
      tls:
        enabled: true
    mds:
      endpoint: https://kafka.dev.svc.cluster.local:8090
      tokenKeyPair:
        secretRef: mds-token
      authentication:
        type: bearer
        bearer:
          secretRef: mds-c3
      tls:
        enabled: true
    connect:
      - name: connect
        url: https://connect.dev.svc.cluster.local:8083
        tls:
          enabled: true
    ksqldb:
      - name: ksql
        url: https://ksql.dev.svc.cluster.local:8088
        tls:
          enabled: true
    schemaRegistry:
      url: https://sr.dev.svc.cluster.local:8081
      tls:
        enabled: true
