apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: client-cert
spec:
  commonName: client
  dnsNames:
    - '*.confluentps.io'
    - '*.svc.cluster.local'

  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
  renewBefore: 24h
  duration: 17520h # two years
  issuerRef:
    kind: ClusterIssuer
    name: ca-issuer
    group: cert-manager.io
  secretName: tls-client
  keystores:
    jks:
      create: true
      passwordSecretRef:
        name: jks-password
        key: jksPassword
    pkcs12:
      create: true
      passwordSecretRef:
        name: jks-password
        key: jksPassword

