apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
  - ../../../../bases/0_external/datadog
  - ../../../../bases/0_external/openldap
  - ../../../../bases/0_external/ingress-nginx
  - ../../../../bases/1_operator
