apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../connectors_generic/replicator

patches:
  - target:
      kind: Connector
      group: platform.confluent.io
    path: rep001.yml
  - target:
      kind: Connector
      name: basereplicator
    patch: |-
      - op: replace
        path: /metadata/name
        value: rep001