apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../02_zookeeper


patches:
  - target:
      group: platform.confluent.io
      version: v1beta1
      kind: Zookeeper
    path: zookeeper.yml

