apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../04_sr


patches:
  - target:
      group: platform.confluent.io
      version: v1beta1
      kind: SchemaRegistry
    path: schemaregistry.yml
