apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - tls-connect.yml     # cacert / fullchain / privkey
  - pscfk-cc-trust.yml  # internal pscfk truststore merged with CCloud fullchain
  - mds-connect.yml     # login credentials
  - connector-secrets.yml
  - connect.yml
