apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../connectors_generic/source/community/with_sr


patches:
  - target:
      kind: Connector
      labelSelector: conntype=source
    path: protobuf.stock_trades.yml
  - target:
      kind: Connector
      name: basesr
    patch: |-
      - op: replace
        path: /metadata/name
        value: protobuf.stocktrades
        
