apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: protobuf.stocktrades
spec:
  name: protobuf.stock_trades
  replicas: 3
  partitionCount: 1
  kafkaClusterRef:
    name: kafka
  kafkaRestClassRef:
    name: default
