apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: protobuf.stocktrades
spec:
  class: "io.confluent.kafka.connect.datagen.DatagenConnector"
  taskMax: 1
  name: protobuf.stock_trades
  configs:
    kafka.topic: protobuf.stock_trades
    quickstart: Stock_Trades
    key.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter: io.confluent.connect.protobuf.ProtobufConverter
    max.interval: "15000"
    iterations: "10000"
    schema.compatibility: "BACKWARD"


