kind: ConfluentRolebinding
apiVersion: platform.confluent.io/v1beta1
metadata:
  name: evntsuper-devread-0
  labels:
    principal: nermin
    role: developerread
    cscope: kafka
spec:
  principal:
    name: nermin
    type: user
  resourcePatterns:
    - name: '*'
      resourceType: Topic
      patternType: LITERAL
    - name: '*'
      resourceType: Group
      patternType: LITERAL
    - name: '_'
      resourceType: Topic
      patternType: PREFIXED
    - name: '_'
      resourceType: Group
      patternType: PREFIXED

  role: DeveloperRead