kind: ConfluentRolebinding
apiVersion: platform.confluent.io/v1beta1
metadata:
  name: evntsuper-sysadm-1
  labels:
    principal: nermin
    role: systemadmin
    cscope: kafkaconnect
spec:
  principal:
    name: nermin
    type: user
  clustersScopeByIds:
    connectClusterId: confluent.connect
  role: SystemAdmin
---
