apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka
spec:
  telemetry:
    global: false


  configOverrides:
    server:
      - kafka.rest.client.client.id=qa.confluentps.kafkarestclient
      - kafka.rest.admin.client.id=qa.confluentps.kafkarestadmin
      - kafka.rest.admin.ssl.keystore.location=/mnt/sslcerts/keystore.p12
      - kafka.rest.admin.ssl.keystore.password=${file:/mnt/sslcerts/jksPassword.txt:jksPassword}
      - kafka.rest.admin.ssl.key.password=${file:/mnt/sslcerts/jksPassword.txt:jksPassword}
      - kafka.rest.admin.ssl.truststore.location=/mnt/sslcerts/truststore.p12
      - kafka.rest.admin.ssl.truststore.password=${file:/mnt/sslcerts/jksPassword.txt:jksPassword}
      - auto.create.topics.enable=true

  dataVolumeCapacity: 150Gi

  podTemplate:
    resources:
      requests:
        cpu: 500m
        memory: 1Gi


  metricReporter:
    enabled: true
    authentication:
      type: mtls
    tls:
      enabled: true
