apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../../../overlays/0_dev/connectors/datagen/avro/campaign_finance
  - ../../../../overlays/0_dev/connectors/datagen/avro/clickstream
  - ../../../../overlays/0_dev/connectors/datagen/avro/credit_cards
  - ../../../../overlays/0_dev/connectors/datagen/avro/fleet_mngnt
  - ../../../../overlays/0_dev/connectors/datagen/avro/product
  - ../../../../overlays/0_dev/connectors/datagen/avro/shoe

