---
apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka
spec:
  replicas: 3
  storageClass:
    name: cfk-storage-delete
  image:
    application: confluentinc/cp-server:7.3.3
    init: confluentinc/confluent-init-container:2.6.0
  dataVolumeCapacity: 50Gi
  passwordEncoder:
    secretRef: password-encoder-secret
  tls:
    secretRef: tls-kafka
  listeners:
    internal:
      authentication:
        type: mtls
        principalMappingRules:
          - RULE:.*CN[\s]?=[\s]?([a-zA-Z0-9.]*)?.*/$1/
      tls:
        enabled: true
  podTemplate:
    tolerations:
      - key: app
        operator: Equal
        value: kafka
        effect: NoSchedule
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: app
                  operator: In
                  values:
                    - kafka
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - kafka
                    - zookeeper

    resources:
      requests:
        cpu: 500m
        memory: 1Gi



---
