apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../07_ksql

patches:

  - target:
      group: platform.confluent.io
      version: v1beta1
      kind: KsqlDB
    path: ksql.yml
