apiVersion: platform.confluent.io/v1beta1
kind: ControlCenter
metadata:
  name: c3
spec:
  authorization:
    type: rbac
  dataVolumeCapacity: 100Gi
  podTemplate:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: app
                  operator: In
                  values:
                    - general
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - c3
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
  dependencies:
    kafka:
      bootstrapEndpoint: kafka.confluent.svc.cluster.local:9073
      authentication:
        type: oauthbearer
        oauthbearer:
          secretRef: mds-c3
      tls:
        enabled: true
    mds:
      endpoint: https://kafka.confluent.svc.cluster.local:8090
      tokenKeyPair:
        secretRef: mds-token
      authentication:
        type: bearer
        bearer:
          secretRef: mds-c3
      tls:
        enabled: true
    connect:
      - name: connect
        url: https://connect.confluent.svc.cluster.local:8083
        tls:
          enabled: true
    ksqldb:
      - name: ksql
        url: https://ksql.confluent.svc.cluster.local:8088
        tls:
          enabled: true
#        authentication:
#          type: basic
#          basic:
#            secretRef: mds-c3
    schemaRegistry:
      url: https://sr.confluent.svc.cluster.local:8081
      tls:
        enabled: true