apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ora-data
  labels:
    app: oracle19
spec:
  storageClassName: cfk-storage-delete
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
