---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zookeeper-cert
spec:
  commonName: zookeeper
  dnsNames:
    - 'zookeeper'

    - 'zookeeper.confluent'
    - 'zookeeper.dev'
    - 'zookeeper.test'
    - 'zookeeper.prod'
    - 'zookeeper.qa'
    - 'zookeeper.dr'

    - 'zookeeper.confluent.svc'
    - 'zookeeper.dev.svc'
    - 'zookeeper.test.svc'
    - 'zookeeper.qa.svc'
    - 'zookeeper.prod.svc'
    - 'zookeeper.dr.svc'

    - 'zookeeper.confluent.svc.cluster.local'
    - 'zookeeper.dev.svc.cluster.local'
    - 'zookeeper.test.svc.cluster.local'
    - 'zookeeper.prod.svc.cluster.local'
    - 'zookeeper.qa.svc.cluster.local'
    - 'zookeeper.dr.svc.cluster.local'

    - '*.zookeeper.confluent.svc.cluster.local'
    - '*.zookeeper.dev.svc.cluster.local'
    - '*.zookeeper.test.svc.cluster.local'
    - '*.zookeeper.prod.svc.cluster.local'
    - '*.zookeeper.qa.svc.cluster.local'
    - '*.zookeeper.dr.svc.cluster.local'

    - '*.confluent.svc.cluster.local'
    - '*.dev.svc.cluster.local'
    - '*.test.svc.cluster.local'
    - '*.qa.svc.cluster.local'
    - '*.prod.svc.cluster.local'
    - '*.dr.svc.cluster.local'

    - 'zookeeper.kafka.confluentps.io'
    - 'zookeeper.confluent.kafka.confluentps.io'
    - 'zookeeper.dev.kafka.confluentps.io'
    - 'zookeeper.test.kafka.confluentps.io'
    - 'zookeeper.qa.kafka.confluentps.io'
    - 'zookeeper.prod.kafka.confluentps.io'
    - 'zookeeper.dr.kafka.confluentps.io'
    - 'zookeeper.confluent.kafka.confluentps.io'
    - 'zookeeper.dr.kafka.confluentps.io'
    - 'zookeeper.dev.kafka.confluentps.io'
    - 'zookeeper.test.kafka.confluentps.io'
    - 'zookeeper.qa.kafka.confluentps.io'
    - 'zookeeper.prod.kafka.confluentps.io'
    - 'zookeeper.kafka.confluentps.io'
    - 'zookeeper.confluent.gke.confluentps.io'
    - 'zookeeper.dr.gke.confluentps.io'
    - 'zookeeper.dev.gke.confluentps.io'
    - 'zookeeper.test.gke.confluentps.io'
    - 'zookeeper.qa.gke.confluentps.io'
    - 'zookeeper.prod.gke.confluentps.io'
    - 'zookeeper.gke.confluentps.io'
    - 'zookeeper.confluent.eks.confluentps.io'
    - 'zookeeper.dr.eks.confluentps.io'
    - 'zookeeper.dev.eks.confluentps.io'
    - 'zookeeper.test.eks.confluentps.io'
    - 'zookeeper.qa.eks.confluentps.io'
    - 'zookeeper.prod.eks.confluentps.io'
    - 'zookeeper.eks.confluentps.io'
    - '*.zookeeper.kafka.confluentps.io'
    - '*.zookeeper.confluent.kafka.confluentps.io'
    - '*.zookeeper.dev.kafka.confluentps.io'
    - '*.zookeeper.test.kafka.confluentps.io'
    - '*.zookeeper.qa.kafka.confluentps.io'
    - '*.zookeeper.prod.kafka.confluentps.io'
    - '*.zookeeper.dr.kafka.confluentps.io'

    - 'localhost'
  issuerRef:
    kind: ClusterIssuer
    name: ca-issuer
    group: cert-manager.io
  secretName: tls-zookeeper
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
  renewBefore: 24h
  duration: 17520h # two years

---