apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../06_krp

patches:
  - target:
      group: platform.confluent.io
      version: v1beta1
      kind: KafkaRestProxy
    path: krp.yml
