apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../2_zookeeper
  - ../../3_kafka
  - ../../4_sr
  - ../../5_connect
  - ../../6_krp
  - ../../7_ksql
  - ../../8_c3

patches:
  - target:
      group: platform.confluent.io
      version: v1beta1
      kind: Zookeeper
    path: patch/zookeeper.yml

  - target:
      group: platform.confluent.io
      version: v1beta1
      kind: Kafka
    path: patch/kafka.yml

  - target:
      group: platform.confluent.io
      version: v1beta1
      kind: SchemaRegistry
    path: patch/schemaregistry.yml

  - target:
      group: platform.confluent.io
      version: v1beta1
      kind: Connect
    path: patch/connect.yml

  - target:
      group: platform.confluent.io
      version: v1beta1
      kind: KsqlDB
    path: patch/ksql.yml

  - target:
      group: platform.confluent.io
      version: v1beta1
      kind: KafkaRestProxy
    path: patch/krp.yml

  - target:
      group: platform.confluent.io
      version: v1beta1
      kind: ControlCenter
    path: patch/c3.yml

