apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../connectors_generic/source/community/with_sr


patches:
  - target:
      kind: Connector
      labelSelector: conntype=source
    path: avro-fld.yml
  - target:
      kind: Connector
      name: basesr
    patch: |-
      - op: replace
        path: /metadata/name
        value: avro.field.mngnt.description
        
