apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace-dev.yml
  - namespace-test.yml
  - license-secret.yml
  - cfk-storage-delete.yml



helmCharts:
  - name: confluent-for-kubernetes
    repo: https://packages.confluent.io/helm
    version: 0.771.13
    releaseName: confluent-operator
    namespace: cfk-operator
    valuesFile: values.yml
    includeCRDs: true


