apiVersion: platform.confluent.io/v1beta1
kind: SchemaRegistry
metadata:
  name: sr
spec:
  authorization:
    type: rbac
  podTemplate:
    resources:
      requests:
        cpu: 100m
        memory: 216Mi
  dependencies:
    mds:
      endpoint: https://kafka.dev.svc.cluster.local:8090
      tokenKeyPair:
        secretRef: mds-token
      authentication:
        type: bearer
        bearer:
          secretRef: mds-sr
      tls:
        enabled: true
    kafka:
      authentication:
        type: oauthbearer
        oauthbearer:
          secretRef: mds-sr
      bootstrapEndpoint: kafka.dev.svc.cluster.local:9073
      tls:
        enabled: true
  configOverrides:
    server:
      - confluent.metadata.enable.server.urls.refresh=false
      - kafka.rest.confluent.metadata.enable.server.urls.refresh=false
