apiVersion: v1
kind: Pod
metadata:
  name: kpod
  namespace: dev
  annotations:
    prometheus.io/port: "7778"
    prometheus.io/scrape: "true"
spec:
  containers:
    - name: kpod
      image: dedovicnermin/pscfk-kpod:1.0.0
      resources:
        requests:
          cpu: 500m
          memory: 516Mi

