apiVersion: platform.confluent.io/v1beta1
kind: SchemaRegistry
metadata:
  name: sr
spec:
  authorization:
    type: rbac
  podTemplate:
    labels:
      tags.datadoghq.com/env: "test"
      tags.datadoghq.com/site: "gke"
    annotations:
      ad.datadoghq.com/tags: |
        {"env": "test","application": "confluent-ps-cfk", "site": "gke"}
    resources:
      requests:
        cpu: 100m
        memory: 216Mi
  dependencies:
    mds:
      endpoint: https://kafka.test.svc.cluster.local:8090
      tokenKeyPair:
        secretRef: mds-token
      authentication:
        type: bearer
        bearer:
          secretRef: mds-sr
      tls:
        enabled: true
    kafka:
      authentication:
        type: oauthbearer
        oauthbearer:
          secretRef: mds-sr
      bootstrapEndpoint: kafka.test.svc.cluster.local:9073
      tls:
        enabled: true
  configOverrides:
    server:
      - confluent.metadata.enable.server.urls.refresh=false
      - kafka.rest.confluent.metadata.enable.server.urls.refresh=false
