apiVersion: platform.confluent.io/v1beta1
kind: KafkaRestProxy
metadata:
  name: krp
spec:
  authorization:
    type: rbac
  podTemplate:
    labels:
      tags.datadoghq.com/env: "prod"
      tags.datadoghq.com/site: "gke"
    annotations:
      ad.datadoghq.com/tags: |
        {"env": "prod","application": "confluent-ps-cfk", "site": "gke"}
    resources:
      requests:
        cpu: 1.0
        memory: 1Gi
  configOverrides:
    server:
      - confluent.metadata.enable.server.urls.refresh=false
      - kafka.rest.confluent.metadata.enable.server.urls.refresh=false
  dependencies:
    mds:
      endpoint: https://kafka.prod.svc.cluster.local:8090
      tokenKeyPair:
        secretRef: mds-token
      authentication:
        type: bearer
        bearer:
          secretRef: mds-krp
      tls:
        enabled: true
    kafka:
      authentication:
        type: oauthbearer
        oauthbearer:
          secretRef: mds-krp
      tls:
        enabled: true
      bootstrapEndpoint: kafka.prod.svc.cluster.local:9073
    interceptor:
      configs:
        - confluent.monitoring.interceptor.bootstrap.servers=kafka.prod.svc.cluster.local:9073
      producer:
        authentication:
          type: oauthbearer
          oauthbearer:
            secretRef: mds-krp
        bootstrapEndpoint: kafka.prod.svc.cluster.local:9073
        tls:
          enabled: true
      consumer:
        authentication:
          type: oauthbearer
          oauthbearer:
            secretRef: mds-krp
        bootstrapEndpoint: kafka.prod.svc.cluster.local:9073
        tls:
          enabled: true
