apiVersion: platform.confluent.io/v1beta1
kind: KsqlDB
metadata:
  name: ksql
spec:
  tls:
    secretRef: tls-ksql
  authorization:
    type: rbac

  podTemplate:
    labels:
      tags.datadoghq.com/env: "prod"
      tags.datadoghq.com/site: "gke"
    annotations:
      ad.datadoghq.com/tags: |
        {"env": "prod","application": "confluent-ps-cfk", "site": "gke"}
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
  dependencies:
    schemaRegistry:
      url: https://sr.prod.svc.cluster.local:8081
      tls:
        enabled: true
    connect:
      url: https://connect.prod.svc.cluster.local:8083
      tls:
        enabled: true
    kafka:
      discovery:
        name: kafka
      tls:
        enabled: true
      authentication:
        type: mtls
    mds:
      endpoint: https://kafka.prod.svc.cluster.local:8090
      tokenKeyPair:
        secretRef: mds-token
      authentication:
        type: bearer
        bearer:
          secretRef: mds-ksql
      tls:
        enabled: true

    interceptor:
      enabled: true

  telemetry:
    global: false


  configOverrides:
    server:
      - ksql.logging.processing.rows.include=true
      - ksql.logging.processing.stream.auto.create=true
      - ksql.logging.processing.stream.name=KPL
      - ksql.logging.processing.topic.auto.create=true
      - ksql.logging.processing.topic.partitions=1
      - ksql.logging.processing.topic.replication.factor=3
      - ksql.access.validator.enable=on
      - confluent.metadata.server.urls.fail.on.401=true
      - confluent.metadata.bootstrap.server.urls=https://kafka.prod.svc.cluster.local:8090
      - confluent.metadata.ssl.keystore.location=/mnt/sslcerts/keystore.p12
      - confluent.metadata.ssl.keystore.password=${file:/mnt/sslcerts/jksPassword.txt:jksPassword}
      - confluent.metadata.ssl.key.password=${file:/mnt/sslcerts/jksPassword.txt:jksPassword}
      - confluent.metadata.ssl.endpoint.identification.algorithm=HTTPS
#      - confluent.metadata.enable.server.urls.refresh=false
      - access.control.allow.origin=*
      - access.control.allow.methods=GET,POST,HEAD
      - access.control.allow.headers=X-Requested-With,Content-Type,Accept,Origin,Authorization
      - ssl.keystore.location=/mnt/sslcerts/keystore.p12
      - ssl.keystore.password=${file:/mnt/sslcerts/jksPassword.txt:jksPassword}
      - ssl.key.password=${file:/mnt/sslcerts/jksPassword.txt:jksPassword}

      - ksql.streams.consumer.client.id=ksql.prod.confluentps.consumerclient
      - consumer.confluent.monitoring.interceptor.bootstrap.servers=kafka.prod.svc.cluster.local:9073
      - producer.confluent.monitoring.interceptor.bootstrap.servers=kafka.prod.svc.cluster.local:9073
      - ksql.streams.admin.client.id=ksql.prod.confluentps.adminclient


    log4j:
      - log4j.appender.stdout=org.apache.log4j.ConsoleAppender
      - log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
      - |
        log4j.appender.stdout.layout.ConversionPattern=[%d] %p %m (%c:%L)%n
      - |
        log4j.logger.processing=ERROR, stdout
      - log4j.additivity.processing=false

  internalTopicReplicationFactor: 3

