apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../05_connect

patches:
  - target:
      group: platform.confluent.io
      version: v1beta1
      kind: Connect
    path: connect.yml
