apiVersion: platform.confluent.io/v1beta1
kind: KafkaRestClass
metadata:
  name: krc-cloud
spec:
  kafkaClusterRef:
    name: kafka
  kafkaRest:
    endpoint: https://pkc-k1622.us-west-2.aws.confluent.cloud:443 #changeme
    kafkaClusterID: lkc-gkq5or                                    #changeme
    authentication:
      type: basic
      basic:
        secretRef: restclass-ccloud

