apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../../bases/connectors/replicator/dev_to_test

patches:
  - target:
      kind: Connector
      group: platform.confluent.io
    path: rep001.yml