apiVersion: platform.confluent.io/v1beta1
kind: Connector
metadata:
  name: rep001
spec:
  configs:
    topic.whitelist: leaderboard.players,leaderboard.products,leaderboard.scorecards,leaderboard.scores
    src.consumer.group.id: replicator.test
    src.kafka.bootstrap.servers: kafka.dev.svc.cluster.local:9073
    src.kafka.sasl.jaas.config: |
      org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required metadataServerUrls="https://kafka.dev.svc.cluster.local:8090" username="${file:/mnt/secrets/mds-replicator/bearer.txt:username}" password="${file:/mnt/secrets/mds-replicator/bearer.txt:password}";
