apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: avro.clickstream.events
spec:
  replicas: 3
  partitionCount: 1
  kafkaClusterRef:
    name: kafka
  kafkaRestClassRef:
    name: default

