apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../connectors_generic/sink/premium/with_sr


patches:
  - target:
      kind: Connector
      labelSelector: conntype=sink
      name: base
    path: adl2s.yml