apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces/namespace-dev.yml
  - namespaces/namespace-test.yml
  - license-secret.yml
  - gke/storageclass-gke-delete.yml



helmCharts:
  - name: confluent-for-kubernetes
    repo: https://packages.confluent.io/helm
    version: 0.824.2
    releaseName: confluent-operator
    namespace: cfk-operator
    valuesFile: values.yml
    includeCRDs: true


