apiVersion: platform.confluent.io/v1beta1
kind: SchemaExporter
metadata:
  name: se001
spec:

  sourceCluster:
    schemaRegistryClusterRef:
      name: sr
  destinationCluster:
    schemaRegistryRest:
      endpoint: https://changeme
      authentication:
        type: basic
        basic:
          secretRef: ccloud-sr-creds

  contextType: NONE
