apiVersion: platform.confluent.io/v1beta1
kind: KafkaRestProxy
metadata:
  name: krp
spec:
  authorization:
    type: rbac
  license:
    globalLicense: true
  podTemplate:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: app
                  operator: In
                  values:
                    - general
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - krp
            topologyKey: kubernetes.io/hostname
    resources:
      requests:
        cpu: 500m
        memory: 516Mi
  replicas: 1
  image:
    application: confluentinc/cp-kafka-rest:7.4.0
    init: confluentinc/confluent-init-container:2.6.0
  tls:
    secretRef: tls-krp
  configOverrides:
    jvm:
      - -XX:+UseG1GC
  dependencies:
    mds:
      authentication:
        bearer:
          secretRef: mds-krp
        type: bearer
      endpoint: https://kafka:8090
      tokenKeyPair:
        secretRef: mds-token
      tls:
        enabled: true


    kafka:
      bootstrapEndpoint: kafka:9073
      authentication:
        type: oauthbearer
        oauthbearer:
          secretRef: mds-krp
      tls:
        enabled: true
    schemaRegistry:
      url: https://sr:8081
      tls:
        enabled: true
      authentication:
        type: basic
        basic:
          secretRef: mds-krp
    interceptor:
      enabled: true
      publishMs: 60000
      configs:
        - confluent.monitoring.interceptor.bootstrap.servers=kafka:9073
      producer:
        authentication:
          type: oauthbearer
          oauthbearer:
            secretRef: mds-krp
        bootstrapEndpoint: kafka:9073
        tls:
          enabled: true
      consumer:
        authentication:
          type: oauthbearer
          oauthbearer:
            secretRef: mds-krp
        bootstrapEndpoint: kafka:9073
        tls:
          enabled: true


