apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cfk-storage-delete
provisioner: dobs.csi.digitalocean.com
parameters:
  volumeMode: Block
  fstype: ext4
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
---