kind: ConfluentRolebinding
apiVersion: platform.confluent.io/v1beta1
metadata:
  name: readonly-devwrite-0
  labels:
    principal: readonlyusers
    role: devwrite
    cscope: kafka

spec:
  principal:
    name: readonlyusers
    type: group
  resourcePatterns:
    - name: _confluent-metrics
      resourceType: Topic
      patternType: PREFIXED
  role: DeveloperWrite
