kind: ConfluentRolebinding
apiVersion: platform.confluent.io/v1beta1
metadata:
  name: readonly-devread-1
  labels:
    principal: readonlyusers
    role: developerread
    cscope: kafkasr

spec:
  principal:
    name: readonlyusers
    type: group
  clustersScopeByIds:
    schemaRegistryClusterId: id_sr_confluent
  resourcePatterns:
    - name: '*'
      resourceType: Subject
      patternType: LITERAL
  role: DeveloperRead