kind: ConfluentRolebinding
apiVersion: platform.confluent.io/v1beta1
metadata:
  name: readonly-resown-0
  labels:
    principal: readonlyusers
    role: resourceowner
    cscope: kafkaksql

spec:
  principal:
    name: readonlyusers
    type: group
  clustersScopeByIds:
    ksqlClusterId: confluent.ksql_
  resourcePatterns:
    - name: ksql-cluster
      resourceType: KsqlCluster
      patternType: LITERAL
  role: ResourceOwner
