apiVersion: platform.confluent.io/v1beta1
kind: ClusterLink
metadata:
  name: cfkcl-dest
  annotations:
    prometheus.io/path: "/metrics"
    prometheus.io/port: "7778"
    prometheus.io/scrape: "true"
spec:

  name: cfkcl
  sourceInitiatedLink:
    linkMode: Destination
  destinationKafkaCluster:
    kafkaRestClassRef:
      name: krc-cloud
      namespace: dev
    tls:
      enabled: true
      secretRef: ccloud-tls-certs

  sourceKafkaCluster:
    kafkaRestClassRef:
      name: default
      namespace: dev
    bootstrapEndpoint: kafka:9073

