apiVersion: platform.confluent.io/v1beta1
kind: Connect
metadata:
  name: connect
spec:
  connectorOverridePolicy: All
  license:
    globalLicense: true
  podTemplate:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: app
                  operator: In
                  values:
                    - general
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - connect
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
  replicas: 1
  image:
    application: dedovicnermin/cfk-connect:1.1.0
    init: confluentinc/confluent-init-container:2.6.0
  tls:
    secretRef: tls-connect
  configOverrides:
    server:
      - log.retention.hours=4
    jvm:
      - -XX:+UseG1GC
  connectorTLSCerts:
    - secretRef: tls-connect
    - secretRef: tls-nejra
    - secretRef: tls-nermin
    - secretRef: tls-niyi
    - secretRef: tls-client
    - secretRef: tls-admin1
    - secretRef: tls-admin2
    - secretRef: tls-dev1
    - secretRef: tls-dev2
    - secretRef: tls-dev3
  mountedSecrets:
    - secretRef: mds-nejra
    - secretRef: mds-nermin
    - secretRef: mds-niyi
    - secretRef: mds-client
    - secretRef: mds-admin1
    - secretRef: mds-admin2
    - secretRef: mds-dev1
    - secretRef: mds-dev2
    - secretRef: mds-dev3